version: '3.8'

services:
  db:
    image: 'postgres:14-alpine'
    expose:
      - "5432/tcp"
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
